<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Comment\Form\Comment'                               => __DIR__ . '/src/Comment/Form/Comment.php',
    'Comment\Form\CommentFilter'                         => __DIR__ . '/src/Comment/Form/CommentFilter.php',
    'Comment\Event\CommentEvent'                         => __DIR__ . '/src/Comment/Event/CommentEvent.php',
    'Comment\Model\CommentAdministration'                => __DIR__ . '/src/Comment/Model/CommentAdministration.php',
    'Comment\Model\CommentWidget'                        => __DIR__ . '/src/Comment/Model/CommentWidget.php',
    'Comment\Model\CommentBase'                          => __DIR__ . '/src/Comment/Model/CommentBase.php',
    'Comment\Model\CommentNestedSet'                     => __DIR__ . '/src/Comment/Model/CommentNestedSet.php',
    'Comment\Controller\CommentAdministrationController' => __DIR__ . '/src/Comment/Controller/CommentAdministrationController.php',
    'Comment\View\Widget\CommentLastUserCommentsWidget'  => __DIR__ . '/src/Comment/View/Widget/CommentLastUserCommentsWidget.php',
    'Comment\View\Widget\CommentWidget'                  => __DIR__ . '/src/Comment/View/Widget/CommentWidget.php',
    'Comment\View\Widget\CommentLastCommentsWidget'      => __DIR__ . '/src/Comment/View/Widget/CommentLastCommentsWidget.php',
    'Comment\View\Widget\AbstractCommentWidget'          => __DIR__ . '/src/Comment/View/Widget/AbstractCommentWidget.php',
    'Comment\View\Helper\CommentProcessAdminComment'     => __DIR__ . '/src/Comment/View/Helper/CommentProcessAdminComment.php',
    'Comment\View\Helper\CommentCommenterName'           => __DIR__ . '/src/Comment/View/Helper/CommentCommenterName.php',
    'Comment\View\Helper\CommentCommenterEmail'          => __DIR__ . '/src/Comment/View/Helper/CommentCommenterEmail.php',
    'Comment\View\Helper\CommentProcessComment'          => __DIR__ . '/src/Comment/View/Helper/CommentProcessComment.php',
    'Comment\Module'                                     => __DIR__ . '/Module.php',
    'Comment\Test\CommentBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
];
