<?php echo $this->form()->openTag($this->comment_form->setAttribute('id', "")) ?>

    <?php if ($this->status && $this->status != 'success'): ?>
        <?php if ($this->status == 'disapproved'): ?>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php echo $this->translate('Your comment will be available after approving') ?>
            </div>
        <?php else: ?>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php echo $this->translate('Error occured, please try again later') ?>
            </div>
        <?php endif ?>
    <?php endif ?>

    <?php echo $this->formRow($this->comment_form->get('comment')->removeAttribute('id')->setLabel('') ) ?>

    <?php if ($this->enable_captcha): ?>
        <?php echo $this->formRow($this->comment_form->get('captcha')->removeAttribute('id')) ?>
    <?php endif ?>

    <?php echo $this->formRow($this->comment_form->get('csrf')->removeAttribute('id')) ?>
    <hr />
    <?php echo $this->formSubmit($this->comment_form->get('submit')->removeAttribute('id')) ?>
<?php echo $this->form()->closeTag() ?>