<?php $this->declareVars('commentPage', 'userPage', 'commenterName', 'commenterUrl') ?>
<?php $this->userPage = $this->pageUrl('user', [], null, true) ?>

<div id="user-last-comments">
    <?php foreach($this->comments as $comment): ?>
        <div class="media">
            <div class="media-body">
                 <p>
                    <?php if ($comment->reply_id): ?>
                        <?php echo $this->translate('Reply to') ?>:
                        <?php 
                            $this->commenterName = $this->commentCommenterName([
                                'guest_id' => $comment->reply_guest_id,
                                'name' => $comment->reply_guest_name,
                                'registred_nickname' => $comment->reply_nickname,
                                'user_id' => $comment->reply_user_id
                            ]);

                            $this->commenterUrl = $comment->reply_user_id && false !== $this->userPage
                                ? $this->url('page', ['page_name' => $this->userPage, 'slug' => $comment->reply_slug], ['force_canonical' => true])
                                : null;
                        ?>
 
                        <?php if ($this->commenterUrl): ?>
                            <a href="<?php echo $this->commenterUrl ?>">
                                <?php echo $this->escapeHtml($this->commenterName) ?>
                            </a>
                        <?php else: ?>
                            <?php echo $this->escapeHtml($this->commenterName) ?>
                        <?php endif ?>
                    <?php endif ?>

                    <time datetime="<?php echo $this->escapeHtmlAttr(date('Y-m-d H:i', $comment->created)) ?>">
                        <?php echo $this->applicationHumanDate($comment->created) ?>
                    </time>
                </p>
                <p>
                    <?php if (mb_strlen($comment->comment) <= $this->visible_chars): ?>
                        <?php echo  $this->commentProcessComment($comment->comment) ?>
                    <?php else: ?>
                        <span><?php echo $this->commentProcessComment(mb_substr($comment->comment, 0, $this->visible_chars)) ?><span class="comment-text-hidden"><?php echo $this->commentProcessComment(mb_substr($comment->comment, $this->visible_chars)) ?></span></span>
                        <a class="comment-more" href="#">
                            <?php echo $this->translate('Show more ...') ?>
                        </a>
                    <?php endif ?>
                </p>
                <?php $this->commentPage = $this->pageUrl($comment->page_slug, [], null, false, $comment->slug) ?>
                <?php if (false !== $this->commentPage): ?>
                    <p>
                        <a href="<?php echo $this->url('page', ['page_name' => $this->commentPage, 'slug' => $comment->slug], ['force_canonical' => true]) ?>#comment-<?php echo (int) $comment->id ?>">
                            <?php echo $this->translate('View on page') ?>
                        </a>
                   </p>
                <?php endif ?>
            </div>
        </div>
    <?php endforeach ?>
</div>