<?php use Comment\Model\CommentNestedSet as CommentNestedSetModel; ?>

<?php $this->declareVars('extraActions', 'subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Edit the comment') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->translate('List of comments')) ?>

<!-- render a header -->
<?php echo $this->render('comment/comment-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of comments'),
            'controller' => 'comments-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'edit_comment' => [
            'name' => $this->subPageTitle,
            'controller' => 'comments-administration',
            'action' => 'edit-comment',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'comments-administration',
        'action' => 'delete-comments',
        'name' => $this->translate('Delete the comment'),
        'check_acl' => true,
        'confirm' => $this->translate('Comment will be deleted with his replies. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'comments' : [{$this->comment['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'comments-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'hide_action' => CommentNestedSetModel::COMMENT_STATUS_ACTIVE == $this->comment['active'],
        'controller' => 'comments-administration',
        'action' => 'approve-comments',
        'name' => $this->translate('Approve the comment'),
        'check_acl' => true,
        'confirm' => $this->translate('Comment will be approved. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'comments' : [{$this->comment['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'comments-administration', 'action' => 'edit-comment', 'slug' => $this->comment['id']], ['force_canonical' => true])}'}) }"
    ],
    [
        'hide_action' => CommentNestedSetModel::COMMENT_STATUS_NOT_ACTIVE == $this->comment['active'],
        'controller' => 'comments-administration',
        'action' => 'disapprove-comments',
        'name' => $this->translate('Disapprove the comment'),
        'check_acl' => true,
        'confirm' => $this->translate('Comment will be disapproved. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'comments' : [{$this->comment['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'comments-administration', 'action' => 'edit-comment', 'slug' => $this->comment['id']], ['force_canonical' => true])}'}) }"
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
   <?php if (!$this->extraActions): ?> 
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('General info'),
                'body' => $this->partial('partial/form', ['form' => $this->comment_form])
            ]) ?>
        </div>
    <?php else: ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('General info'),
                'body' => $this->partial('partial/form', ['form' => $this->comment_form])
            ]) ?>
        </div>
       <div class="col-md-4">
           <?php echo $this->extraActions ?>
       </div>
    <?php endif ?>
</div>